### ISSUE TITLE
It looks like it stopped working in XCode 6.4

### ISSUE THREAD

**Issue by tomnaz** [holtwick/HOStringSense-for-Xcode#12]

**Comment by tomnaz** [comment]
I have commited a fix.

**Comment by 7934345** [comment]
Not work for me, Xcode 6.4

**Comment by ashaitek** [comment]
Not working in Xcode 6.4 tried by downloading the project and build/compile it and using Alcatraz, both ways I deleted the plugin manually

**Comment by holtwick** [comment]
Hi, thanks a lot for letting me know. I submitted a patch. Please try again.

**Comment by ashaitek** [comment]
Now works - Thanks

**Comment by 7934345** [comment]
Thx, works again!
