### ISSUE TITLE
Do not work in Xcode 7.2

### ISSUE THREAD

**Issue by DimonDeveloper** [holtwick/HOStringSense-for-Xcode#18]
Do not work in Xcode 7.2

**Comment by DimonDeveloper** [comment]
Just add F41BD31E-2683-44B8-AE7F-5F09E919790E in Info.plist to DVTPlugInCompatibilityUUIDs

**Comment by holtwick** [comment]
Fixed now in 14c78cee85c8e1a56a5bda3feb18e254ea1296ef
