### ISSUE TITLE
Popover closes while editing

### ISSUE THREAD

**Issue by gerald-coddut** [holtwick/HOStringSense-for-Xcode#5]
Since a short time I'm unable to use the plugin correctly. When I open the popup everything is fine, but when I start to typ (even 1 character) something it automatically closes.

I've no idea why this happens. Tried reinstalling the plugin, reopen XCode enz. to no avail however...

**Comment by crystalt** [comment]
Also had this problem. Fixed it by removing surrounding quotes in `stringDidChange:` method in HOStringHelper.m:

```objc
            [self.textView insertText:[NSString stringWithFormat:@"\"%@\"", result]
                     replacementRange:self.selectedStringRange];
```

```objc
            [self.textView insertText:[NSString stringWithFormat:@"%@", result]
                     replacementRange:self.selectedStringRange];
```
